{
  "ai_label": "Stela_of_Neskhonsu",
  "latitude": 29.9947,
  "longitude": 31.1189,
  "era": "Third Intermediate Period — 21st Dynasty",
  "category": "Artifact",
  "cover_image": "/uploads/monuments/Stela_of_Neskhonsu.png",
  "names": {
    "en": "Stela of Neskhonsu",
    "ar": "لوحة نيسخونسو",
    "ru": "Стела Несхонсу",
    "de": "Stele von Neskhonsu",
    "fr": "Stèle de Neskhonsou",
    "es": "Estela de Neskhonsu",
    "zh": "内斯孔苏石碑"
  },
  "descriptions": {
    "en": "This round-topped painted wooden stela of Neskhons was found at Deir el-Bahri in an area dedicated for the burials of the priests of god Montu.  Neskhons' husband was a priest of Montu. The stela is framed by the arched body of the sky goddess Nut who touches the earth with the tips of her fingers and her feet. A winged sun disc spans above hieroglyphs that read Behdety (a form of Horus of Edfu). The central scene on the stela shows Neskhons embraced by goddess Maat as she stands at an altar, her hands are raised in adoration before the falcon-headed god Re-Horakhty and the goddess of the West. On the lower part of the stela, an offering formula asks god Re-Horakhty to grant Neskhons provisions for the afterlife. Neskhons was apparently a descendant of a priestly family, as in the text her father Hormaa is referred to as the 'beloved of the god at Karnak'.",
    "ar": "عُثر على هذه اللوحة الخشبية المزخرفة ذات القمة المستديرة، والتي تُصوّر نيسخونس، في دير البحري، في منطقة مُخصصة لدفن كهنة الإله مونتو. كان زوج نيسخونس كاهنًا لمونتو. تُحيط باللوحة صورة مُقوّسة لإلهة السماء نوت، وهي تلامس الأرض بأطراف أصابعها وقدميها. يمتد قرص شمسي مُجنّح فوق نقوش هيروغليفية تُقرأ بهدتي (أحد أشكال حورس إدفو). يُظهر المشهد المركزي على اللوحة نيسخونس وهي مُحتضنة من قِبل الإلهة ماعت، واقفةً عند مذبح، ويداها مرفوعتان في خشوع أمام الإله رع حور آختي ذي رأس الصقر، وإلهة الغرب. في الجزء السفلي من اللوحة، توجد صيغة تقديم قربان تطلب من الإله رع حور آختي أن يُوفّر لنيسخونس ما تحتاجه في الحياة الآخرة. ويبدو أن نيسخونس كانت من نسل عائلة كهنوتية، حيث يشير النص إلى والدها هورما على أنه \"حبيب الإله في الكرنك\".",
    "ru": "Эта круглая расписная деревянная стела с изображением Несхонс была найдена в Дейр-эль-Бахри, в месте, предназначенном для захоронений жрецов бога Монту. Муж Несхонс был жрецом Монту. Стела обрамлена арочным телом богини неба Нут, которая касается земли кончиками пальцев и ступней. Над иероглифами, читающими Бехдети (одна из форм Гора из Эдфу), расположен крылатый солнечный диск. Центральная сцена на стеле изображает Несхонс, обнимаемую богиней Маат, стоящую у алтаря, с поднятыми в поклонении руками перед богом с головой сокола Ре-Хорахти и богиней Запада. В нижней части стелы находится формула подношения, в которой бог Ре-Хорахти просит даровать Несхонс пропитание для загробной жизни. Несконс, по-видимому, происходила из жреческой семьи, поскольку в тексте её отец Хормаа упоминается как «возлюбленный бога в Карнаке».",
    "de": "Diese runde, bemalte Holzstele der Neskhons wurde in Deir el-Bahari in einem Gräberfeld für die Priester des Gottes Montu gefunden. Neskhons' Ehemann war ebenfalls Priester des Montu. Die Stele wird vom gewölbten Körper der Himmelsgöttin Nut eingerahmt, die mit ihren Finger- und Fußspitzen die Erde berührt. Eine geflügelte Sonnenscheibe spannt sich über Hieroglyphen, die Behdety (eine Form des Horus von Edfu) bedeuten. Die zentrale Szene der Stele zeigt Neskhons, umarmt von der Göttin Maat, die an einem Altar steht und ihre Hände in Anbetung vor dem falkenköpfigen Gott Re-Horakhty und der Göttin des Westens erhebt. Im unteren Teil der Stele bittet eine Opferformel den Gott Re-Horakhty um Versorgung Neskhons' für das Jenseits. Neskhons stammte offenbar aus einer Priesterfamilie, da ihr Vater Hormaa im Text als der „Geliebte des Gottes in Karnak“ bezeichnet wird.",
    "fr": "Cette stèle en bois peint à sommet arrondi de Neskhonsou fut trouvée à Deir el-Bahari, dans une zone réservée aux sépultures des prêtres du dieu Montou. Le mari de Neskhonsou était prêtre de Montou. La stèle est encadrée par le corps arqué de la déesse du ciel Nout, qui touche la terre du bout des doigts et des pieds. Un disque solaire ailé s’étend au-dessus de hiéroglyphes lisant Behedety, une forme d’Horus d’Edfou. La scène centrale montre Neskhonsou embrassée par la déesse Maât, debout devant un autel, les mains levées en adoration devant le dieu à tête de faucon Rê-Horakhty et la déesse de l’Occident. Dans la partie inférieure, une formule d’offrande demande au dieu Rê-Horakhty d’accorder à Neskhonsou des provisions pour l’au-delà. Neskhonsou descendait apparemment d’une famille sacerdotale, car le texte désigne son père Hormaa comme le « bien-aimé du dieu à Karnak ».",
    "es": "Esta estela de madera pintada con parte superior redondeada de Neskhonsu fue hallada en Deir el-Bahari, en una zona dedicada a los enterramientos de los sacerdotes del dios Montu. El esposo de Neskhonsu era sacerdote de Montu. La estela está enmarcada por el cuerpo arqueado de la diosa del cielo Nut, que toca la tierra con las puntas de sus dedos y sus pies. Un disco solar alado se extiende sobre jeroglíficos que dicen Behdety, una forma de Horus de Edfu. La escena central muestra a Neskhonsu abrazada por la diosa Maat mientras está de pie ante un altar, con las manos levantadas en adoración ante el dios con cabeza de halcón Ra-Horakhty y la diosa del Occidente. En la parte inferior, una fórmula de ofrenda pide al dios Ra-Horakhty que conceda provisiones a Neskhonsu para la vida después de la muerte. Neskhonsu aparentemente descendía de una familia sacerdotal, ya que el texto llama a su padre Hormaa «amado del dios en Karnak».",
    "zh": "这件内斯孔苏的圆顶彩绘木碑发现于代尔巴哈里，那里有一片专门用于安葬蒙图神祭司的区域。内斯孔苏的丈夫是一名蒙图祭司。石碑由天空女神努特弓形的身体环绕，她以手指和脚尖触碰大地。带翼太阳圆盘横跨在象形文字上方，文字写着贝赫德提，即埃德富荷鲁斯的一种形态。石碑中央场景表现内斯孔苏被玛阿特女神拥抱，她站在祭坛前，双手举起，向鹰首神拉-哈拉赫提和西方女神表示崇拜。石碑下部的供奉祷文请求拉-哈拉赫提赐予内斯孔苏来世所需的供品。内斯孔苏显然出身于祭司家族，因为文中称她的父亲霍尔玛为“卡纳克神所爱之人”。"
  }
}
